# Experiment 2.1 - Hyperopt to find best classifier

In [5]:
pip install git+https://github.com/hyperopt/hyperopt-sklearn.git

  Cloning https://github.com/hyperopt/hyperopt-sklearn.git to /tmp/pip-req-build-ezpywh0s
  Running command git clone -q https://github.com/hyperopt/hyperopt-sklearn.git /tmp/pip-req-build-ezpywh0s
  Created wheel for hpsklearn: filename=hpsklearn-0.0.3-py3-none-any.whl size=26922 sha256=b7067fea2957c9afd6ebb652739dcd2b047d40a09822a80cc53490c6e01b4c8f
  Stored in directory: /tmp/pip-ephem-wheel-cache-_mgnnuyb/wheels/47/a5/46/9ca750026db9dfa5de4bf4836194554cb0e2e01a245588ea59
Successfully built hpsklearn
Note: you may need to restart the kernel to use updated packages.


In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# import load_data function from helper file 
%load_ext autoreload
%autoreload 2

# fix system path
import sys
sys.path.append("/home/jovyan/work")

In [3]:
from src.features.helper_functions import load_sets

X_train, y_train, X_val, y_val, X_test = load_sets()

https://machinelearningmastery.com/hyperopt-for-automated-machine-learning-with-scikit-learn/

https://github.com/hyperopt/hyperopt-sklearn

In [4]:
from hpsklearn import HyperoptEstimator
from hpsklearn import any_classifier
from hpsklearn import any_preprocessing
from hyperopt import tpe


WARN: OMP_NUM_THREADS=None =>
... If you are using openblas if you are using openblas set OMP_NUM_THREADS=1 or risk subprocess calls hanging indefinitely


In [5]:

# define search
model = HyperoptEstimator(classifier=any_classifier('cla'), preprocessing = [], algo=tpe.suggest, max_evals=50, trial_timeout=30, seed = 42)
# pass an empty list to preprocessing to do nothing

# perform the search
model.fit(X_train, y_train)


# summarize performance
acc = model.score(X_val, y_val)
print("Accuracy: %.3f" % acc)
# summarize the best model
print(model.best_model())

 94%|█████████▍| 16/17 [00:00<?, ?trial/s, best loss=?]

/opt/conda/lib/python3.7/site-packages/xgboost/sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)



[10:19:01] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost_1607604574104/work/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
 95%|█████████▍| 18/19 [00:00<?, ?trial/s, best loss=?]

/opt/conda/lib/python3.7/site-packages/xgboost/sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)



[10:19:53] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost_1607604574104/work/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
 98%|█████████▊| 46/47 [00:00<?, ?trial/s, best loss=?]

/opt/conda/lib/python3.7/site-packages/xgboost/sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)



[10:21:21] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost_1607604574104/work/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
100%|██████████| 50/50 [00:00<00:00, 208.22trial/s, best loss: 0.17578125]
Accuracy: 0.839
{'learner': ExtraTreesClassifier(bootstrap=True, max_depth=2,
                     max_features=0.5114013866515924, n_estimators=1145,
                     n_jobs=1, random_state=1, verbose=False), 'preprocs': (), 'ex_preprocs': ()}


In [19]:
# Train this model again using the above model
from sklearn.ensemble import ExtraTreesClassifier

model = ExtraTreesClassifier(bootstrap=True, max_depth=2, class_weight = "balanced_subsample",
                     max_features=0.5114013866515924, n_estimators=1145,
                     n_jobs=1, random_state=1, verbose=False)

etclf = model.fit(X_train, y_train)

In [20]:
# predict class
y_train_preds = etclf.predict(X_train)
y_val_preds = etclf.predict(X_val)

In [21]:
# predict proabilities
y_train_preds_prob = etclf.predict_proba(X_train)
y_val_preds_prob = etclf.predict_proba(X_val)

In [22]:
from src.features.helper_functions import result_metrics

In [23]:
result_metrics(y_train, y_train_preds,y_train_preds_prob)

Accuracy: 62.41%
Precision: 89.98% 
Recall: 61.70% 
AUC using prediction probabilities: 68.970% 
              precision    recall  f1-score   support

           0       0.26      0.66      0.37      1074
           1       0.90      0.62      0.73      5326

    accuracy                           0.62      6400
   macro avg       0.58      0.64      0.55      6400
weighted avg       0.79      0.62      0.67      6400

Confusion Matrix
[[ 708  366]
 [2040 3286]]


In [24]:
result_metrics(y_val, y_val_preds,y_val_preds_prob)

Accuracy: 62.50%
Precision: 90.78% 
Recall: 61.58% 
AUC using prediction probabilities: 69.769% 
              precision    recall  f1-score   support

           0       0.25      0.67      0.37       257
           1       0.91      0.62      0.73      1343

    accuracy                           0.62      1600
   macro avg       0.58      0.64      0.55      1600
weighted avg       0.80      0.62      0.67      1600

Confusion Matrix
[[173  84]
 [516 827]]


In [25]:
# save model
from src.features.helper_functions import save_model

In [26]:
save_model(etclf, 'rez_etclf_1')

Model saved succesfully


In [ ]:
# predict on test set


In [27]:
# create an output for kaggle testing anyway.
y_test_preds = etclf.predict(X_test)
y_test_preds_prob = etclf.predict_proba(X_test)

In [28]:
print(y_test_preds)
print(y_test_preds_prob)

[0 0 1 ... 0 1 0]
[[0.55198684 0.44801316]
 [0.50364994 0.49635006]
 [0.3517363  0.6482637 ]
 ...
 [0.58697257 0.41302743]
 [0.32636914 0.67363086]
 [0.55008323 0.44991677]]


In [29]:
unique_elements, counts_elements = np.unique(y_test_preds, return_counts=True)
print(np.asarray((unique_elements, counts_elements)))

[[   0    1]
 [1619 2180]]


In [30]:
1619/2180

0.7426605504587156

In [31]:
from src.features.helper_functions import create_output

In [32]:
output = create_output(y_test_preds_prob)

In [33]:
output

Id  TARGET_5Yrs
0        0     0.448013
1        1     0.496350
2        2     0.648264
3        3     0.689108
4        4     0.442623
...    ...          ...
3794  3794     0.623098
3795  3795     0.524807
3796  3796     0.413027
3797  3797     0.673631
3798  3798     0.449917

[3799 rows x 2 columns]

In [34]:
# save to csv
output.to_csv('../data/processed/output_etclf_wk3.csv',index=False)

# KAGGLE 0.69803

### Try using the extra trees classifier as a base to adaboost

In [35]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold

In [36]:
# define base model
base = model # from above
# define ensemble model
adaboost = AdaBoostClassifier(base_estimator=base,n_estimators = 150, learning_rate = 0.1)

In [39]:
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# evaluate the model and collect the results
scores = cross_val_score(model, X_train, y_train, scoring='roc_auc', cv=cv, n_jobs=-1)


In [41]:
scores

array([0.73965037, 0.68243587, 0.69465729, 0.67186267, 0.6599218 ,
       0.6989006 , 0.70962128, 0.68025968, 0.66424742, 0.6472083 ,
       0.66221879, 0.69718223, 0.71924041, 0.65795795, 0.67451035,
       0.63696937, 0.70112782, 0.72606864, 0.68736076, 0.67898914,
       0.69143098, 0.68643369, 0.67321281, 0.756834  , 0.71301573,
       0.66628676, 0.6810951 , 0.6769702 , 0.66551796, 0.63077833])

In [42]:
np.mean(scores)

0.684398877235343

In [44]:
# lets use it - see what happens
etclf_adaboost = adaboost.fit(X_train, y_train)

In [46]:
# predict class
y_train_preds = etclf_adaboost.predict(X_train)
y_val_preds = etclf_adaboost.predict(X_val)

In [47]:
# predict proabilities
y_train_preds_prob = etclf_adaboost.predict_proba(X_train)
y_val_preds_prob = etclf_adaboost.predict_proba(X_val)

In [48]:
result_metrics(y_train, y_train_preds,y_train_preds_prob)

Accuracy: 65.08%
Precision: 90.92% 
Recall: 64.48% 
AUC using prediction probabilities: 72.650% 
              precision    recall  f1-score   support

           0       0.28      0.68      0.40      1074
           1       0.91      0.64      0.75      5326

    accuracy                           0.65      6400
   macro avg       0.59      0.66      0.57      6400
weighted avg       0.80      0.65      0.69      6400

Confusion Matrix
[[ 731  343]
 [1892 3434]]


In [49]:
result_metrics(y_val, y_val_preds,y_val_preds_prob)

Accuracy: 64.06%
Precision: 90.34% 
Recall: 64.04% 
AUC using prediction probabilities: 70.570% 
              precision    recall  f1-score   support

           0       0.25      0.64      0.36       257
           1       0.90      0.64      0.75      1343

    accuracy                           0.64      1600
   macro avg       0.58      0.64      0.56      1600
weighted avg       0.80      0.64      0.69      1600

Confusion Matrix
[[165  92]
 [483 860]]


In [50]:
save_model(etclf, 'rez_etclf_adaboost')

Model saved succesfully


In [ ]:
# predict on test set


In [51]:
# create an output for kaggle testing anyway.
y_test_preds = etclf_adaboost.predict(X_test)
y_test_preds_prob = etclf_adaboost.predict_proba(X_test)

In [52]:
print(y_test_preds)
print(y_test_preds_prob)

[0 0 1 ... 0 1 0]
[[0.50389802 0.49610198]
 [0.50422836 0.49577164]
 [0.48052584 0.51947416]
 ...
 [0.50795938 0.49204062]
 [0.479326   0.520674  ]
 [0.50453972 0.49546028]]


In [53]:
unique_elements, counts_elements = np.unique(y_test_preds, return_counts=True)
print(np.asarray((unique_elements, counts_elements)))

[[   0    1]
 [1560 2239]]


In [54]:
1560/2239

0.6967396158999554

In [31]:
from src.features.helper_functions import create_output

In [55]:
output = create_output(y_test_preds_prob)

In [56]:
output

Id  TARGET_5Yrs
0        0     0.496102
1        1     0.495772
2        2     0.519474
3        3     0.542378
4        4     0.494874
...    ...          ...
3794  3794     0.520148
3795  3795     0.500218
3796  3796     0.492041
3797  3797     0.520674
3798  3798     0.495460

[3799 rows x 2 columns]

In [57]:
# save to csv
output.to_csv('../data/processed/output_etclf_adaboost_wk3.csv',index=False)

# KAGGLE 0.70974