# Experiment 3.4 - SVM

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# import load_data function from helper file 
%load_ext autoreload
%autoreload 2

# fix system path
import sys
sys.path.append("/home/jovyan/work")

In [3]:
from src.features.helper_functions import load_sets

X_train, y_train, X_val, y_val, X_test = load_sets()

In [4]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
# fit and transform training set
X_train = scaler.fit_transform(X_train)
# only transform validation set
X_val = scaler.transform(X_val)

In [9]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear', probability=True)
svclassifier.fit(X_train, y_train)

SVC(kernel='linear', probability=True)

In [10]:
# predict class
y_train_preds = svclassifier.predict(X_train)
y_val_preds = svclassifier.predict(X_val)

In [11]:
# predict proabilities
y_train_preds_prob = svclassifier.predict_proba(X_train)
y_val_preds_prob = svclassifier.predict_proba(X_val)

In [12]:
from src.features.helper_functions import result_metrics
result_metrics(y_train, y_train_preds,y_train_preds_prob)

Accuracy: 83.22%
Precision: 83.22% 
Recall: 100.00% 
AUC using prediction probabilities: 48.385% 
              precision    recall  f1-score   support

           0       0.00      0.00      0.00      1074
           1       0.83      1.00      0.91      5326

    accuracy                           0.83      6400
   macro avg       0.42      0.50      0.45      6400
weighted avg       0.69      0.83      0.76      6400

Confusion Matrix
[[   0 1074]
 [   0 5326]]


/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [13]:
result_metrics(y_val, y_val_preds,y_val_preds_prob)

Accuracy: 83.94%
Precision: 83.94% 
Recall: 100.00% 
AUC using prediction probabilities: 46.567% 
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       257
           1       0.84      1.00      0.91      1343

    accuracy                           0.84      1600
   macro avg       0.42      0.50      0.46      1600
weighted avg       0.70      0.84      0.77      1600

Confusion Matrix
[[   0  257]
 [   0 1343]]


/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Not very good, perhaps a different kernel would do better

In [14]:
svclassifier_rbf = SVC(kernel='rbf', probability=True)
svclassifier_rbf.fit(X_train, y_train)

SVC(probability=True)

In [15]:
# predict class
y_train_preds = svclassifier_rbf.predict(X_train)
y_val_preds = svclassifier_rbf.predict(X_val)

In [16]:
# predict proabilities
y_train_preds_prob = svclassifier_rbf.predict_proba(X_train)
y_val_preds_prob = svclassifier_rbf.predict_proba(X_val)

In [17]:
from src.features.helper_functions import result_metrics
result_metrics(y_train, y_train_preds,y_train_preds_prob)

Accuracy: 83.23%
Precision: 83.23% 
Recall: 100.00% 
AUC using prediction probabilities: 83.326% 
              precision    recall  f1-score   support

           0       1.00      0.00      0.00      1074
           1       0.83      1.00      0.91      5326

    accuracy                           0.83      6400
   macro avg       0.92      0.50      0.46      6400
weighted avg       0.86      0.83      0.76      6400

Confusion Matrix
[[   1 1073]
 [   0 5326]]


In [18]:
result_metrics(y_val, y_val_preds,y_val_preds_prob)

Accuracy: 83.94%
Precision: 83.94% 
Recall: 100.00% 
AUC using prediction probabilities: 60.510% 
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       257
           1       0.84      1.00      0.91      1343

    accuracy                           0.84      1600
   macro avg       0.42      0.50      0.46      1600
weighted avg       0.70      0.84      0.77      1600

Confusion Matrix
[[   0  257]
 [   0 1343]]


/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Bit better, but not much, try sigmoid kernel

In [19]:
svclassifier_sig = SVC(kernel='sigmoid', probability=True)
svclassifier_sig.fit(X_train, y_train)

SVC(kernel='sigmoid', probability=True)

In [20]:
# predict class
y_train_preds = svclassifier_sig.predict(X_train)
y_val_preds = svclassifier_sig.predict(X_val)

In [21]:
# predict proabilities
y_train_preds_prob = svclassifier_sig.predict_proba(X_train)
y_val_preds_prob = svclassifier_sig.predict_proba(X_val)

In [22]:
from src.features.helper_functions import result_metrics
result_metrics(y_train, y_train_preds,y_train_preds_prob)

Accuracy: 74.55%
Precision: 84.19% 
Recall: 85.47% 
AUC using prediction probabilities: 58.881% 
              precision    recall  f1-score   support

           0       0.22      0.20      0.21      1074
           1       0.84      0.85      0.85      5326

    accuracy                           0.75      6400
   macro avg       0.53      0.53      0.53      6400
weighted avg       0.74      0.75      0.74      6400

Confusion Matrix
[[ 219  855]
 [ 774 4552]]


In [23]:
result_metrics(y_val, y_val_preds,y_val_preds_prob)

Accuracy: 74.56%
Precision: 84.67% 
Recall: 85.11% 
AUC using prediction probabilities: 57.998% 
              precision    recall  f1-score   support

           0       0.20      0.19      0.20       257
           1       0.85      0.85      0.85      1343

    accuracy                           0.75      1600
   macro avg       0.52      0.52      0.52      1600
weighted avg       0.74      0.75      0.74      1600

Confusion Matrix
[[  50  207]
 [ 200 1143]]
